add the logic to help in case of nomad instance shutdown

diff --git a/docker/s5ci-start.in b/docker/s5ci-start.in
--- a/docker/s5ci-start.in
+++ b/docker/s5ci-start.in
@@ -56,7 +56,8 @@ echo "$(date): s5ci database rebuild" >>${TIMELINE_LOG}
 # put the transaction mode to WAL for somewhat better performance
 echo PRAGMA journal_mode=WAL | sqlite3 /s5ci/db/s5ci.sqlite3
 RUST_LOG=debug RUST_BACKTRACE=1 /usr/local/bin/s5ci -c ${S5CI_CONFIG_PATH} rebuild-database >>${DB_REBUILD_LOG}
-echo PRAGMA journal_mode=DEETE | sqlite3 /s5ci/db/s5ci.sqlite3
+RUST_LOG=debug RUST_BACKTRACE=1 /usr/local/bin/s5ci -c ${S5CI_CONFIG_PATH} mark-active-as-failed >>${DB_REBUILD_LOG}
+echo PRAGMA journal_mode=DELETE | sqlite3 /s5ci/db/s5ci.sqlite3
 
 export NOMAD_AGENT_LOG="${LOG_DIR}/nomad-agent.log"
 export NOMAD_LOG="${LOG_DIR}/nomad.log"
@@ -73,19 +74,43 @@ else
 fi
 
 echo "$(date): starting background back-sync loop" >>${TIMELINE_LOG}
+setsid -w rsync -az -e 'ssh -p23 -i/secrets/s5ci-key' --recursive /local/html ${STORAGE_USER}@${STORAGE_HOST}: 2>>${BACK_RSYNC_LOG} >>${BACK_RSYNC_LOG}
+
 while (true); do
 	sleep 1
         echo "$(date): rsync back" >>${BACK_RSYNC_LOG}
 	# rsync a tiny file upstream each second so people know we are alive
 	printf '{ "nomad_alloc_id": "%s", "rsync_timestamp": "%s"}' ${NOMAD_ALLOC_ID} $(date '+%s') > /local/jobs/heartbeat.json
-	# rsync the html UI
-	rsync -az -e 'ssh -p23 -i/secrets/s5ci-key' --recursive /local/jobs ${STORAGE_USER}@${STORAGE_HOST}: 2>>${BACK_RSYNC_LOG} >>${BACK_RSYNC_LOG} 
-	# it is static data but won't hurt.
-	rsync -az -e 'ssh -p23 -i/secrets/s5ci-key' --recursive /local/html ${STORAGE_USER}@${STORAGE_HOST}: 2>>${BACK_RSYNC_LOG} >>${BACK_RSYNC_LOG}
+	# rsync the html UI and data, do not delete
+	rsync -az -e 'ssh -p23 -i/secrets/s5ci-key' --recursive --max-delete=-1 --exclude workspace /local/jobs ${STORAGE_USER}@${STORAGE_HOST}: 2>>${BACK_RSYNC_LOG} >>${BACK_RSYNC_LOG} 
 done &
 
+#
+# this part runs with signals intercepted, for cleanup
+#
 
-echo "$(date): EXECOK: startup finished" >>${TIMELINE_LOG}
+
+echo "$(date): EXECOK: S5CI startup finished, now run" >>${TIMELINE_LOG}
+
+trap sigint INT
+trap '' PIPE
+trap '' HUP
+trap cleanup QUIT
+trap cleanup ABRT
+trap cleanup TERM
+
+sigint()
+{
+	echo "$(date): got SIGINT" >>${TIMELINE_LOG}
+}
+
+cleanup()
+{
+	echo "$(date): got SIGTERM" >>${TIMELINE_LOG}
+        echo "Caught signal, cleaning up"
+        echo "Done cleanup"
+}
+
 
 # execute the meta-s5ci
 RUST_LOG=debug RUST_BACKTRACE=1 /usr/local/bin/s5ci -c ${META_S5CI_CONFIG_PATH} 2>>${META_S5CI_LOG} >>${META_S5CI_LOG} &
@@ -93,9 +118,14 @@ RUST_LOG=debug RUST_BACKTRACE=1 /usr/local/bin/s5ci -c ${META_S5CI_CONFIG_PATH} 
 # execute the s5ci. 
 RUST_LOG=debug RUST_BACKTRACE=1 /usr/local/bin/s5ci -c ${S5CI_CONFIG_PATH}
 
+echo "$(date): S5CI finished, status: $?" >>${TIMELINE_LOG}
+echo "$(date): final rsync"
+setsid rsync -az -e 'ssh -p23 -i/secrets/s5ci-key' --max-delete=-1 --exclude workspace --recursive /local/jobs ${STORAGE_USER}@${STORAGE_HOST}: 2>>${BACK_RSYNC_LOG} >>${BACK_RSYNC_LOG} 
+echo "$(date): final rsync finished" >>${TIMELINE_LOG}
+
 # the empty cycle in the end
-while true; do
-	date
+for i in $(seq 60 -1 1); do
+	echo "$(date): winding down, $i sec remaining">>${TIMELINE_LOG}
 	sleep 1
 done
 
